### ISSUE TITLE
Typos in data sharing page

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/california-data-collaborative.github.io#3]
Looks to be some typos on the data sharing page.

"Australia’s national government **provides a central information platform collates and analyses** national near real-time data from agencies and authorities monitoring reservoirs, stream levels, diversions, and groundwater levels. "  - needs comma?

"Australia could also serve as a model for the public benefit corporation r**equired under to create and** manage the water accounting system, as a similar entity, the now **defunctNational** Water Commision, was created in order to make water management viable across the country. " - missing words and spacing?

**Comment by vipassana** [comment]
Thanks! Fixed these.
